# Generated by Django 4.2.11 on 2024-04-04 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_car', models.CharField(max_length=32)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('year', models.DateTimeField(auto_now_add=True, verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('with_photo', models.BooleanField()),
                ('color', models.CharField(choices=[('черный ', 'черный '), ('красный', 'красный'), ('голубой', 'голубой'), ('серый', 'серый'), ('белый', 'белый')], max_length=16, verbose_name='Цвет')),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('box', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика')], max_length=16, verbose_name='Коробка')),
                ('drive', models.CharField(choices=[('Задний', 'Задний'), ('Передний', 'Передний'), ('Полный привод', 'Полный привод')], max_length=16, verbose_name='Привод')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_marka', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', models.CharField(max_length=100)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marka')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_number', models.IntegerField(default=0)),
                ('buy_now', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
