# Generated by Django 4.2.11 on 2024-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='title_car_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
